### ISSUE TITLE
After successful compile, getting java.lang.ClassNotFoundException: io.quarkus.runtime.util.StringUtil

### ISSUE THREAD

**Issue by notsharable** [hpehl/quarkus-grpc-extension#2]
Hi all,

I am new to quarkus and already enthusiast. 

I have maven-installed quarkus-grpc-extension 999-SNAPSHOT with quarkus 0.20.0 .  

I keep getting the following error: when executing ./mvnw  compile quarkus:dev,   Not sure what is wrong.

Listening for transport dt_socket at address: 5005
02:19:11,328 INFO  [io.qua.dep.QuarkusAugmentor] Beginning quarkus augmentation
02:19:11,432 ERROR [io.qua.dev.DevModeMain] Failed to start quarkus: java.lang.NoClassDefFoundError: io/quarkus/runtime/util/StringUtil
        at io.quarkus.deployment.configuration.ConfigDefinition.registerConfigRoot(ConfigDefinition.java:183)
        at io.quarkus.deployment.ExtensionLoader.loadStepsFrom(ExtensionLoader.java:180)
        at io.quarkus.deployment.ExtensionLoader.loadStepsFrom(ExtensionLoader.java:137)
        at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:75)
        at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:107)
        at io.quarkus.dev.DevModeMain.doStart(DevModeMain.java:171)
        at io.quarkus.dev.DevModeMain.main(DevModeMain.java:89)
Caused by: java.lang.ClassNotFoundException: io.quarkus.runtime.util.StringUtil
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 7 more

02:19:11,433 ERROR [io.qua.dev.DevModeMain] Failed to start Quarkus, attempting to start hot replacement endpoint to recover

**Comment by hpehl** [comment]
I guess that's because of the different versions: 999-SNAPSHOT vs. 0.20.0. I'll try to align my version with Quarkus 0.20.0.

**Comment by notsharable** [comment]
Just to provide some more context. I have put the grpc extension under directory quarkus\build-parent and mvn install it from there as its pom declares quarkus-build-parent as parent pom.  With 999-SNAPSHOT as version.

**Comment by notsharable** [comment]
Overriding quarkus core (which contains the runtime library) in my maven module that uses grpc extension, the problem is gone. So your guess is correct. I will test fix once ready.

Bellow is the dependecy added to my module pom:
``<dependency>
	    <groupId>io.quarkus</groupId>
	    <artifactId>quarkus-core</artifactId>
	    <version>0.20.0</version>
	</dependency>``

**Comment by hpehl** [comment]
I've aligned the version to the latest stable Quarkus version. This should fix the issue. Can you please verify?

**Comment by hpehl** [comment]
Closing, since this extension is no longer supported. See README.md
